@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(editor, "Content editor", "A marketeer or developer who edits or creates forms.")
Person_Ext(visitor, "Visitor", "A (potential) customer who visits a form.")
System_Ext(api, "API", "Provides endpoints (LMS / OBS / Occasions)")
System_Ext(ext_data, "External Data", "Stores images and info on data tagging")
System_Boundary(lgp, "Leadgen Platform") {
    Container(wa, "Web Application", "Node JS", "Provides endpoints for FE and generates static forms.")
    Container(spa, "Single Page Application", "React", "Shows a form to a customer via their web browser.")
    Container(cms, "CMS UI", "React", "Provides a UI for the client to edit forms and related car model data.")
    Container(db, "Database", "Relational Database Schema", "Stores forms and car model data")

    Rel(spa, wa, "Uses endpoints", "JSON/HTTPS")
    Rel(wa, cms, "Uses form data", "JSON/HTTPS")
    Rel(db, cms, "Reads & writes to", "JDBC")
    Rel(wa, spa, "Delivers")
}

Rel(editor, cms, "Uses")
Rel(editor, ext_data, "Uses")
Rel(visitor, spa, "Uses")
Rel(spa, api, "Uses")
@enduml
