@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(editor, "Content editor", "Marketeer or developer that edits/creates content data.")
Person_Ext(visitor, "Visitor", "A website visitor who fills out a form.")
Container(leadgen, "Lead-Gen Platform", "Contains form and car model data that allows it to generate forms.")
System(cmp, "Shared Components Library", "Contains shared UI components.")
System(osb, "OSB API", "Provides endpoints for services.")
System(lms, "LMS Services API", "Provides form and taxation configurations.")
System(occasions, "Occasions API", "Provides occasions data.")
System_Ext(img, "Image Database", "Contains official images of car models.")
System(formhandler, "Form Handler", "Handles form submits.")
System(dealer, "Dealer Service", "Provides all dealers.")
System(finance, "Finance Service", "Provides finance products and calculations.")

Rel(editor, leadgen, "Edits content")
Rel(visitor, leadgen, "Uses form")
Rel(leadgen, cmp, "Uses components")
Rel(leadgen, osb, "Uses endpoints")
Rel(leadgen, lms, "Uses")
Rel(leadgen, occasions, "Uses occasion data")
Rel(editor, img, "Uses images")
Rel(osb, formhandler, "Uses")
Rel(osb, dealer, "Uses")
Rel(osb, finance, "Uses")
@enduml
