@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(editor, "Content editor", "Marketeer or developer that edits/creates content data.")
Person_Ext(visitor, "Visitor", "A website visitor who fills out a form.")
Container(leadgen, "Lead-Gen Platform", "Contains form and car model data that allows it to generate forms.")
System(cmp, "Shared Components Library", "Contains shared UI components.")
System(osb, "OSB API", "Provides endpoints for form handler, dealer service and finance service.")
System(lms, "LMS Services API", "Provides form and taxation configurations.")
System(occasions, "Occasions API", "Provides occasions data.")
System_Ext(img, "Image Database", "Contains official images of car models.")
System(data, "Data tagging sheet", "Contains the TNGA data tagging values.")

Rel(editor, leadgen, "Edits content on")
Rel(visitor, leadgen, "Uses form from")
Rel(leadgen, cmp, "Uses components from")
Rel(leadgen, osb, "Uses endpoints of")
Rel(leadgen, lms, "Uses")
Rel(leadgen, occasions, "Uses occasion data")
Rel(editor, img, "Downloads images from")
Rel(editor, data, "Uses")
@enduml
